all: info

info:
	echo 'to run something type "make demo"'

demo:
	python ../src/artemisia.py -l mypackage.mysubpackage.mysubsubpackage -i data -y "AVG(normalized_temperature)" -x version_number -c room